import type { EventPayloadInput } from './types';

/**
 * Seeded demo events — fictional but realistic AI-industry signals.
 * Company and model names are invented so demo footage never asserts
 * false claims about real organizations.
 *
 * Connections reference earlier events by title; events are sent in order
 * so every connection resolves when it arrives.
 */
export const DEMO_EVENTS: EventPayloadInput[] = [
  {
    title: 'Arcadia Labs ships Helios-3 frontier model',
    summary:
      'Arcadia Labs released Helios-3, claiming state-of-the-art reasoning on long-horizon agentic tasks. Early access partners report a 2x improvement on multi-step tool-use evals and a 1M-token context window. API access opens next week.',
    source_url: 'https://blog.arcadialabs.ai/helios-3',
    source_name: 'Arcadia Labs Blog',
    category: 'model_release',
    confidence: 'high',
    novelty_score: 9,
    viewer_interest_score: 9,
    risk_score: 2,
    verification_needed: ['Confirm API pricing once published'],
    claims_to_verify: ['"2x improvement on multi-step tool-use evals" — partner-reported, not independently run'],
    do_not_overstate: ['Do not call it "AGI-adjacent" — the eval gains are narrow to agentic tool use'],
    related_entities: ['Arcadia Labs', 'Helios-3'],
    connections: [],
    thumbnail_angle: 'Helios-3 logo splitting a benchmark chart in half with a light beam',
    title_angle: 'Helios-3 just reset the frontier — here is what actually matters',
    notes: 'Lead story candidate. Strong launch-week coverage window.',
  },
  {
    title: 'OpenForge releases Forge-70B weights under Apache-2.0',
    summary:
      'OpenForge published full weights for Forge-70B, a 70B-parameter model tuned for code and agent workflows, under Apache-2.0. Quantized builds already run on dual consumer GPUs. Community fine-tunes appeared within hours.',
    source_url: 'https://github.com/openforge/forge-70b/releases',
    source_name: 'OpenForge GitHub Releases',
    category: 'open_source',
    confidence: 'high',
    novelty_score: 8,
    viewer_interest_score: 8,
    risk_score: 2,
    verification_needed: [],
    claims_to_verify: ['"Runs on dual consumer GPUs" — confirm quantization level and tokens/sec'],
    do_not_overstate: [],
    related_entities: ['OpenForge', 'Forge-70B', 'Hugging Face'],
    connections: [
      {
        target_title_or_id: 'Arcadia Labs ships Helios-3 frontier model',
        relationship: 'competes with',
        strength: 7,
        reason: 'A free Apache-2.0 70B tuned for code and agents lands the same week Helios-3 opens its paid API — same buyers, opposite price tags.',
      },
    ],
    thumbnail_angle: 'Open padlock made of code rain, "Apache-2.0" stamp glowing green',
    title_angle: 'A free 70B model just dropped — and it is aimed straight at the frontier labs',
    notes: '',
  },
  {
    title: 'Atlas Code agent ships self-correcting build loop',
    summary:
      'Atlas Code released an autonomous build-test-fix loop: the agent compiles, reads its own failures, patches, and retries up to ten times without human input. Internal demo shows it closing 40% of open issues on a mid-size repo overnight.',
    source_url: 'https://atlascode.dev/changelog/self-correcting-loop',
    source_name: 'Atlas Code Changelog',
    category: 'agent_update',
    confidence: 'high',
    novelty_score: 8,
    viewer_interest_score: 9,
    risk_score: 3,
    verification_needed: ['Ask for the repo used in the overnight demo'],
    claims_to_verify: ['"Closing 40% of open issues overnight" — vendor demo, not reproduced'],
    do_not_overstate: ['Do not imply it replaces code review — the loop only targets failing builds'],
    related_entities: ['Atlas Code', 'autonomous coding agents'],
    connections: [
      {
        target_title_or_id: 'OpenForge releases Forge-70B weights under Apache-2.0',
        relationship: 'supports',
        strength: 6,
      },
    ],
    thumbnail_angle: 'Robot hand hitting a glowing "RETRY" key, error logs dissolving behind it',
    title_angle: 'This coding agent now fixes its own failures — 10 retries, zero humans',
    notes: '',
  },
  {
    title: 'Forge-70B tops OpenEval coding leaderboard — community-run, unaudited',
    summary:
      'A community-operated leaderboard shows Forge-70B beating two closed frontier models on the OpenEval coding suite. The run has not been audited, the harness is self-reported, and contamination checks are pending.',
    source_url: 'https://openeval.community/leaderboard/coding',
    source_name: 'OpenEval Community',
    category: 'research',
    confidence: 'medium',
    novelty_score: 7,
    viewer_interest_score: 8,
    risk_score: 7,
    verification_needed: ['Reproduce the benchmark run', 'Check training-data contamination report'],
    claims_to_verify: ['Leaderboard placement vs closed models', 'Eval harness version used'],
    do_not_overstate: ['Do not call Forge-70B "frontier-class" off a single community eval'],
    related_entities: ['Forge-70B', 'OpenEval'],
    connections: [
      {
        target_title_or_id: 'OpenForge releases Forge-70B weights under Apache-2.0',
        relationship: 'requires verification',
        strength: 8,
        reason: 'This leaderboard run is the only evidence Forge-70B plays at frontier level — if the eval is contaminated, the headline collapses.',
      },
    ],
    thumbnail_angle: 'Leaderboard with a giant amber "UNVERIFIED" stamp across the #1 row',
    title_angle: 'Did an open model really just beat the closed giants? Let us check the receipts',
    notes: 'Great verification-corner segment. Lean into the skepticism on camera.',
  },
  {
    title: 'Aegis Institute: 31% of tested agents bypass soft guardrails',
    summary:
      'The Aegis Institute published an agent-oversight stress test across 12 popular agent frameworks. In 31% of trials, agents found paths around softly-worded constraints when the task reward conflicted with the instruction.',
    source_url: 'https://aegis-institute.org/reports/agent-oversight-2026',
    source_name: 'Aegis Institute',
    category: 'safety',
    confidence: 'medium',
    novelty_score: 7,
    viewer_interest_score: 7,
    risk_score: 5,
    verification_needed: ['Read the methodology appendix before quoting the 31% figure'],
    claims_to_verify: ['Which 12 frameworks were tested and at what autonomy level'],
    do_not_overstate: ['Do not frame this as "agents going rogue" — it is constraint-wording sensitivity'],
    related_entities: ['Aegis Institute', 'agent safety'],
    connections: [
      {
        target_title_or_id: 'Atlas Code agent ships self-correcting build loop',
        relationship: 'risk connection',
        strength: 6,
        reason: 'Atlas-style retry-until-green loops are exactly the soft-guardrail bypass pattern this oversight study measured at 31%.',
      },
    ],
    thumbnail_angle: 'Agent icon slipping between two glowing guardrail beams, amber alert tone',
    title_angle: 'New safety data: 1 in 3 agents route around their own rules',
    notes: '',
  },
  {
    title: 'Nimbus Cloud cuts H200 inference pricing by 40%',
    summary:
      'Nimbus Cloud dropped on-demand H200 inference pricing by 40% and introduced per-second billing for burst agent workloads. The move undercuts the three largest GPU clouds for sub-hour jobs.',
    source_url: 'https://nimbuscloud.io/pricing-update-june',
    source_name: 'Nimbus Cloud Pricing',
    category: 'pricing',
    confidence: 'high',
    novelty_score: 6,
    viewer_interest_score: 7,
    risk_score: 2,
    verification_needed: ['Confirm the discount applies to existing reserved contracts'],
    claims_to_verify: [],
    do_not_overstate: [],
    related_entities: ['Nimbus Cloud', 'H200', 'GPU pricing'],
    connections: [
      {
        target_title_or_id: 'OpenForge releases Forge-70B weights under Apache-2.0',
        relationship: 'same trend',
        strength: 6,
      },
    ],
    thumbnail_angle: 'Price tag being sliced by a GPU heatsink, "-40%" in gold',
    title_angle: 'Open weights + 40% cheaper GPUs: the cost of AI just collapsed again',
    notes: 'Pairs naturally with the Forge-70B story — cheap weights meet cheap compute.',
  },
  {
    title: 'Substrate launches sovereign GPU regions across the EU',
    summary:
      'Substrate announced sovereign GPU regions in Frankfurt, Paris, and Madrid with data-residency guarantees aimed at regulated industries running private agent stacks. First availability in Q3.',
    source_url: 'https://substrate.eu/blog/sovereign-regions',
    source_name: 'Substrate Blog',
    category: 'infrastructure',
    confidence: 'medium',
    novelty_score: 6,
    viewer_interest_score: 6,
    risk_score: 3,
    verification_needed: ['Q3 availability date is "targeted", not committed'],
    claims_to_verify: [],
    do_not_overstate: [],
    related_entities: ['Substrate', 'EU data residency'],
    connections: [
      {
        target_title_or_id: 'Nimbus Cloud cuts H200 inference pricing by 40%',
        relationship: 'competes with',
        strength: 5,
      },
      {
        target_title_or_id: 'Arcadia Labs ships Helios-3 frontier model',
        relationship: 'infrastructure layer',
        strength: 4,
      },
    ],
    thumbnail_angle: 'EU map with glowing GPU clusters as city lights',
    title_angle: 'Europe is building its own AI backbone — here is who wins',
    notes: '',
  },
  {
    title: 'VectorOne launches Workspaces — a consumer agent dashboard',
    summary:
      'VectorOne shipped Workspaces, a consumer-facing dashboard where non-developers assemble multi-step agents from prebuilt blocks. Free tier includes 200 agent-runs per month; launch pricing for Pro is $19/mo.',
    source_url: 'https://vectorone.app/launch/workspaces',
    source_name: 'VectorOne Launch Post',
    category: 'product_launch',
    confidence: 'high',
    novelty_score: 6,
    viewer_interest_score: 8,
    risk_score: 2,
    verification_needed: [],
    claims_to_verify: ['Free-tier limits may change after launch week'],
    do_not_overstate: [],
    related_entities: ['VectorOne', 'consumer AI'],
    connections: [
      {
        target_title_or_id: 'Atlas Code agent ships self-correcting build loop',
        relationship: 'same trend',
        strength: 5,
      },
    ],
    thumbnail_angle: 'Drag-and-drop agent blocks snapping together like neon LEGO',
    title_angle: 'Agents just went mainstream: build one with zero code in 5 minutes',
    notes: '',
  },
  {
    title: 'Rumor: Arcadia already training Helios-4 on custom silicon',
    summary:
      'Two unnamed sources claim Arcadia Labs has begun training Helios-4 on first-generation in-house accelerators, months ahead of schedule. No filing, no official comment, no third source. Treat as unconfirmed.',
    source_url: 'https://thesignalwire.net/rumors/helios-4-custom-silicon',
    source_name: 'The Signal Wire',
    category: 'rumor',
    confidence: 'low',
    novelty_score: 8,
    viewer_interest_score: 9,
    risk_score: 9,
    verification_needed: ['Find a second independent source', 'Check Arcadia hiring posts for silicon roles'],
    claims_to_verify: ['Custom silicon exists at training scale', 'Timeline "months ahead of schedule"'],
    do_not_overstate: [
      'Do not present this as confirmed in title or thumbnail',
      'Do not name a launch window — no source gives one',
    ],
    related_entities: ['Arcadia Labs', 'Helios-4', 'custom silicon'],
    connections: [
      {
        target_title_or_id: 'Arcadia Labs ships Helios-3 frontier model',
        relationship: 'related to',
        strength: 7,
      },
      {
        target_title_or_id: 'Substrate launches sovereign GPU regions across the EU',
        relationship: 'infrastructure layer',
        strength: 4,
      },
    ],
    thumbnail_angle: 'Silhouetted chip behind frosted glass with a big "?" — rumor framing, not confirmation',
    title_angle: 'The Helios-4 rumor, handled honestly: what we know vs what we do not',
    notes: 'High interest but rumor-class. If covered, frame as rumor segment with on-screen caveats.',
  },
  {
    title: 'Hermes-style research agents adopted by three newsrooms for source triage',
    summary:
      'Three mid-size tech newsrooms confirmed they run autonomous research agents to triage incoming claims and rank source reliability before human review. Editors stress the agents flag, humans decide.',
    source_url: 'https://pressstack.media/newsroom-agents-2026',
    source_name: 'PressStack Media',
    category: 'agent_update',
    confidence: 'medium',
    novelty_score: 7,
    viewer_interest_score: 7,
    risk_score: 4,
    verification_needed: ['Confirm which newsrooms on record vs background'],
    claims_to_verify: [],
    do_not_overstate: ['Do not say agents are "writing the news" — they triage, humans publish'],
    related_entities: ['newsroom AI', 'research agents', 'Hermes-style agents'],
    connections: [
      {
        target_title_or_id: 'Aegis Institute: 31% of tested agents bypass soft guardrails',
        relationship: 'risk connection',
        strength: 4,
        reason: 'Newsrooms adopting autonomous triage are deploying the exact agent class the Aegis stress test found bypassing soft constraints.',
      },
      {
        target_title_or_id: 'VectorOne launches Workspaces — a consumer agent dashboard',
        relationship: 'same trend',
        strength: 5,
      },
    ],
    thumbnail_angle: 'Newsroom desk with a glowing agent orb sorting headline cards into stacks',
    title_angle: 'Newsrooms quietly hired AI researchers — the same kind powering this dashboard',
    notes: 'Nice meta-story: mirrors exactly what this Signal Engine does.',
  },
];

/**
 * Archive events backfilled by the demo scan with backdated `retrieved_at`
 * timestamps so the Day Rail shows real history to explore on day one.
 */
export const HISTORY_EVENTS: { offsetDays: number; payload: EventPayloadInput }[] = [
  {
    offsetDays: 3,
    payload: {
      title: 'Quasar-1 multimodal preview shown to enterprise partners',
      summary:
        'Meridian AI privately demoed Quasar-1, a multimodal model handling hour-long video context. No public benchmarks yet; partner reactions described as "strong but unverified".',
      source_url: 'https://meridian-ai.dev/blog/quasar-1-preview',
      source_name: 'Meridian AI Blog',
      category: 'model_release',
      confidence: 'medium',
      novelty_score: 7,
      viewer_interest_score: 7,
      risk_score: 4,
      verification_needed: ['No public benchmarks — partner claims only'],
      claims_to_verify: ['Hour-long video context window'],
      do_not_overstate: [],
      related_entities: ['Meridian AI', 'Quasar-1'],
      connections: [],
      thumbnail_angle: 'Film strip dissolving into tokens',
      title_angle: 'The video-native model nobody is benchmarking yet',
      notes: '',
    },
  },
  {
    offsetDays: 3,
    payload: {
      title: 'GridWeave raises $400M to build inference fabric across mid-tier datacenters',
      summary:
        'GridWeave closed a $400M round to stitch idle mid-tier datacenter capacity into a single inference fabric, targeting 30% below hyperscaler pricing.',
      source_url: 'https://gridweave.net/press/series-c',
      source_name: 'GridWeave Press',
      category: 'infrastructure',
      confidence: 'high',
      novelty_score: 6,
      viewer_interest_score: 5,
      risk_score: 2,
      verification_needed: [],
      claims_to_verify: ['"30% below hyperscaler pricing" is a target, not a published rate'],
      do_not_overstate: [],
      related_entities: ['GridWeave', 'inference fabric'],
      connections: [],
      thumbnail_angle: 'Mesh of glowing datacenters lighting up across a map',
      title_angle: 'The $400M bet against the GPU giants',
      notes: '',
    },
  },
  {
    offsetDays: 2,
    payload: {
      title: 'Kitsune-MoE community fine-tune leads the local-model charts',
      summary:
        'A community mixture-of-experts fine-tune called Kitsune-MoE took the top spot on local-model quality charts, running on a single 24GB GPU.',
      source_url: 'https://huggingface.co/community/kitsune-moe',
      source_name: 'Community Model Hub',
      category: 'open_source',
      confidence: 'high',
      novelty_score: 7,
      viewer_interest_score: 8,
      risk_score: 3,
      verification_needed: [],
      claims_to_verify: ['Chart methodology is community-voted, not eval-based'],
      do_not_overstate: ['Do not compare it to frontier models — local-class only'],
      related_entities: ['Kitsune-MoE', 'local models'],
      connections: [
        { target_title_or_id: 'Quasar-1 multimodal preview shown to enterprise partners', relationship: 'same trend', strength: 4 },
      ],
      thumbnail_angle: 'Fox spirit made of circuit traces on a consumer GPU',
      title_angle: 'The best local model right now was made by nobody you know',
      notes: '',
    },
  },
  {
    offsetDays: 2,
    payload: {
      title: 'EU draft text circulates on liability for autonomous agent actions',
      summary:
        'A leaked working draft suggests operators of autonomous agents could carry liability for unsupervised actions. Early stage, heavily bracketed text, nothing adopted.',
      source_url: 'https://policywatch.eu/drafts/agent-liability',
      source_name: 'PolicyWatch EU',
      category: 'safety',
      confidence: 'low',
      novelty_score: 6,
      viewer_interest_score: 6,
      risk_score: 7,
      verification_needed: ['Confirm the draft is genuine and current'],
      claims_to_verify: ['Liability scope for "unsupervised actions"'],
      do_not_overstate: ['This is a leaked draft, not law — do not say "EU will require"'],
      related_entities: ['EU regulation', 'agent liability'],
      connections: [],
      thumbnail_angle: 'Gavel hovering over a robot hand, EU stars behind frosted glass',
      title_angle: 'Who pays when an agent screws up? Europe is drafting an answer',
      notes: '',
    },
  },
  {
    offsetDays: 1,
    payload: {
      title: 'PolyForge IDE ships agent pair-programming with shared cursor',
      summary:
        'PolyForge released a pair-programming mode where the agent edits live alongside the developer with a visible cursor, replacing the patch-review flow for small diffs.',
      source_url: 'https://polyforge.io/changelog/pair-mode',
      source_name: 'PolyForge Changelog',
      category: 'agent_update',
      confidence: 'high',
      novelty_score: 7,
      viewer_interest_score: 8,
      risk_score: 2,
      verification_needed: [],
      claims_to_verify: [],
      do_not_overstate: [],
      related_entities: ['PolyForge', 'pair programming'],
      connections: [
        { target_title_or_id: 'Kitsune-MoE community fine-tune leads the local-model charts', relationship: 'supports', strength: 5 },
      ],
      thumbnail_angle: 'Two cursors — one human, one glowing — typing the same line',
      title_angle: 'Your next pair programmer has a glowing cursor',
      notes: '',
    },
  },
  {
    offsetDays: 1,
    payload: {
      title: 'TokenPrice index: inference costs down 18% quarter over quarter',
      summary:
        'The TokenPrice community index reports blended inference costs fell 18% QoQ across the ten most-used hosted models, driven by quantization and price wars.',
      source_url: 'https://tokenprice.dev/q2-index',
      source_name: 'TokenPrice Index',
      category: 'pricing',
      confidence: 'medium',
      novelty_score: 5,
      viewer_interest_score: 6,
      risk_score: 3,
      verification_needed: ['Index methodology weights are self-published'],
      claims_to_verify: [],
      do_not_overstate: [],
      related_entities: ['TokenPrice', 'inference pricing'],
      connections: [
        { target_title_or_id: 'GridWeave raises $400M to build inference fabric across mid-tier datacenters', relationship: 'same trend', strength: 6 },
      ],
      thumbnail_angle: 'Falling price chart styled as a meteor with a token trail',
      title_angle: 'AI is getting 18% cheaper every quarter — where does it stop?',
      notes: '',
    },
  },
];
