import type { CreatorBrief } from './types';

/** Serializes a creator brief to clean markdown. Safe to use client-side. */
export function briefToMarkdown(brief: CreatorBrief): string {
  const lines: string[] = [];
  const section = (title: string) => lines.push('', `## ${title}`, '');

  lines.push('# AI Signal Engine — Creator Brief');
  lines.push('');
  lines.push(`> Generated: ${new Date(brief.generated_at).toLocaleString()}`);

  section('Executive Summary');
  lines.push(brief.executive_summary);

  section('Strongest Video Angle');
  lines.push(brief.strongest_angle);

  section('Title Ideas');
  brief.title_ideas.forEach((t, i) => lines.push(`${i + 1}. ${t}`));

  section('Thumbnail Concepts');
  brief.thumbnail_ideas.forEach((t, i) => lines.push(`${i + 1}. ${t}`));

  section('Story Bundles');
  brief.bundles.forEach((b, i) => {
    lines.push(`### ${i + 1}. ${b.name}`, '');
    lines.push(`**Summary:** ${b.summary}`, '');
    lines.push(`**Story arc:** ${b.story_arc}`, '');
    lines.push('**Segments:**');
    b.segment_outline.forEach((s) => lines.push(`- ${s}`));
    lines.push('', `**Recommended title:** ${b.recommended_title}`);
    lines.push(`**Thumbnail idea:** ${b.thumbnail_idea}`, '');
    if (b.verification_checklist.length > 0) {
      lines.push('**Verify before filming:**');
      b.verification_checklist.forEach((v) => lines.push(`- [ ] ${v}`));
      lines.push('');
    }
    if (b.source_urls.length > 0) {
      lines.push('**Sources:**');
      b.source_urls.forEach((u) => lines.push(`- ${u}`));
      lines.push('');
    }
  });

  section('Segment Outline');
  brief.segment_outline.forEach((s) => lines.push(`- ${s}`));

  section('Key Talking Points');
  brief.talking_points.forEach((t) => lines.push(`- ${t}`));

  section('Verification Checklist');
  brief.verification_checklist.forEach((v) => lines.push(`- [ ] ${v}`));

  section('Risky Claims — Do Not Overstate');
  brief.risky_claims.forEach((r) => lines.push(`- ⚠️ ${r}`));

  section('Sources');
  brief.sources.forEach((s) => lines.push(`- [${s.name}](${s.url})`));

  lines.push('', '---', '', '_Generated by AI Signal Engine. Verify everything before publishing._');
  return lines.join('\n');
}
